// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Signature struct {
	ID        uuid.UUID `json:"id"`
	UserID    string    `json:"user_id"`
	Signature string    `json:"signature"`
	Answers   []string  `json:"answers"`
	Questions []string  `json:"questions"`
	Timestamp time.Time `json:"timestamp"`
}
